"""
Job Scanner route — POST /api/job-scan
Accepts a job title, researches tasks via Tavily, runs full WorkScanAI
analysis, saves as a workflow, and returns the workflow ID + n8n JSON.
"""
from fastapi import APIRouter, Depends, HTTPException, Request, Header
from sqlalchemy.orm import Session
from typing import Optional
from pydantic import BaseModel, Field

from app.core.database import get_db
from app.models.workflow import Workflow, Task, Analysis, AnalysisResult, User, _gen_share_code
from app.services.job_scanner import JobScanner
from app.services.ai_analyzer import AIAnalyzer

router = APIRouter()


# ------------------------------------------------------------------
# Request / Response schemas
# ------------------------------------------------------------------

class JobScanRequest(BaseModel):
    job_title: str = Field(..., min_length=2, max_length=100)
    industry: Optional[str] = Field(None, max_length=100)
    analysis_context: Optional[str] = Field("individual")
    hourly_rate: Optional[float] = Field(75.0, gt=0)


class JobScanResponse(BaseModel):
    workflow_id: int
    share_code: str
    job_title: str
    tasks_found: int
    n8n_workflow: dict
    search_used: bool
    message: str

    class Config:
        from_attributes = True


# ------------------------------------------------------------------
# Endpoint
# ------------------------------------------------------------------

@router.post("/job-scan", response_model=JobScanResponse, status_code=201)
async def job_scan(
    request: JobScanRequest,
    http_request: Request,
    db: Session = Depends(get_db),
    x_user_email: Optional[str] = Header(None),
):
    """
    1. Research job tasks via Tavily web search
    2. Extract structured task list via Claude
    3. Save as a workflow + run full AI analysis
    4. Generate n8n workflow JSON
    5. Return workflow_id (for redirect to dashboard) + n8n JSON
    """

    # --- Scan job & extract tasks ---
    try:
        scanner = JobScanner()
        scan_result = scanner.scan_job(
            job_title=request.job_title,
            industry=request.industry,
            analysis_context=request.analysis_context or "individual",
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Job scan failed: {str(e)}")

    tasks = scan_result.get("tasks", [])
    if not tasks:
        raise HTTPException(status_code=422, detail="Could not extract tasks for this job title")

    # --- Persist user ---
    if x_user_email:
        email = x_user_email.lower().strip()
        user = db.query(User).filter(User.email == email).first()
        if not user:
            user = User(email=email)
            db.add(user)
            db.flush()

    # --- Create workflow ---
    workflow = Workflow(
        share_code=_gen_share_code(),
        name=f"{request.job_title} – Job Scanner",
        description=f"Auto-generated by WorkScanAI Job Scanner for role: {request.job_title}",
        input_mode="job_scan",
        analysis_context=request.analysis_context or "individual",
        industry=request.industry,
        user_email=x_user_email.lower().strip() if x_user_email else None,
    )
    db.add(workflow)
    db.flush()


    # --- Create tasks in DB ---
    task_objs = []
    for t in tasks:
        task_obj = Task(
            workflow_id=workflow.id,
            name=t.get("name", "Unknown task"),
            description=t.get("description"),
            frequency=t.get("frequency", "weekly"),
            time_per_task=t.get("time_per_task", 30),
            category=t.get("category", "general"),
            complexity=t.get("complexity", "medium"),
        )
        db.add(task_obj)
        task_objs.append(task_obj)
    db.flush()

    # --- Run AI analysis (same engine as manual workflows) ---
    analyzer = AIAnalyzer()
    task_dicts = [
        {
            "name": t.get("name"),
            "description": t.get("description"),
            "frequency": t.get("frequency", "weekly"),
            "time_per_task": t.get("time_per_task", 30),
            "category": t.get("category", "general"),
            "complexity": t.get("complexity", "medium"),
            "analysis_context": request.analysis_context or "individual",
            "industry": request.industry or "",
        }
        for t in tasks
    ]

    batch_results = analyzer.analyze_tasks_batch(task_dicts)

    tasks_analysis = []
    for task_obj, task_dict, result in zip(task_objs, task_dicts, batch_results):
        result["task"] = task_dict
        result["task_obj"] = task_obj
        tasks_analysis.append(result)

    roi_metrics = analyzer.calculate_roi(tasks_analysis, request.hourly_rate or 75.0)

    # --- Save analysis ---
    analysis = Analysis(
        workflow_id=workflow.id,
        automation_score=roi_metrics["automation_score"],
        hours_saved=roi_metrics["hours_saved"],
        annual_savings=roi_metrics["annual_savings"],
        readiness_score=roi_metrics.get("readiness_score"),
        readiness_data_quality=roi_metrics.get("readiness_data_quality"),
        readiness_process_docs=roi_metrics.get("readiness_process_docs"),
        readiness_tool_maturity=roi_metrics.get("readiness_tool_maturity"),
        readiness_team_skills=roi_metrics.get("readiness_team_skills"),
    )
    db.add(analysis)
    db.flush()

    for ta in tasks_analysis:
        ar = AnalysisResult(
            analysis_id=analysis.id,
            task_id=ta["task_obj"].id,
            ai_readiness_score=ta["ai_readiness_score"],
            score_repeatability=ta.get("score_repeatability"),
            score_data_availability=ta.get("score_data_availability"),
            score_error_tolerance=ta.get("score_error_tolerance"),
            score_integration=ta.get("score_integration"),
            time_saved_percentage=ta.get("time_saved_percentage"),
            recommendation=ta.get("recommendation"),
            difficulty=ta.get("difficulty"),
            estimated_hours_saved=ta.get("estimated_hours_saved"),
            risk_level=ta.get("risk_level"),
            risk_flag=ta.get("risk_flag"),
            agent_phase=ta.get("agent_phase"),
            agent_label=ta.get("agent_label"),
            agent_milestone=ta.get("agent_milestone"),
            orchestration=ta.get("orchestration"),
            countdown_window=ta.get("countdown_window"),
            human_edge_score=ta.get("human_edge_score"),
            pivot_skills=ta.get("pivot_skills"),
            pivot_roles=ta.get("pivot_roles"),
            decision_layer=ta.get("decision_layer"),
        )
        db.add(ar)

    db.commit()

    return JobScanResponse(
        workflow_id=workflow.id,
        share_code=workflow.share_code,
        job_title=request.job_title,
        tasks_found=len(tasks),
        n8n_workflow=scan_result.get("n8n_workflow", {}),
        search_used=scan_result.get("search_used", False),
        message=f"Scanned {len(tasks)} tasks for '{request.job_title}'. Analysis saved.",
    )
