// #37 Richer n8n export — auto-written setup guide per generated workflow.
// Pure, dependency-free: turns an n8n workflow JSON (+ light metadata) into a
// short, human-readable Markdown setup guide. Client-side only; never throws —
// falls back to a minimal guide if the JSON shape is unexpected. This is purely
// ADDITIVE: it never touches or transforms the workflow JSON users import.

export interface SetupGuideInput {
  workflowName: string
  templateName?: string
  taskName?: string
  url?: string
  relevanceReason?: string
  nodeCount?: number
  workflowJson?: unknown
}

interface N8nNodeLike { name?: unknown; type?: unknown }

// Short node-type key -> what the user must configure. Only nodes that usually
// need credentials/config are listed; triggers and logic nodes are skipped.
const CRED_HINTS: Record<string, string> = {
  httpRequest: 'Set the request URL and authentication (API key, header, or OAuth) on the node.',
  webhook: 'Copy the webhook URL n8n generates and point your source system at it.',
  gmail: 'Connect a Google/Gmail credential (n8n -> Credentials).',
  googleSheets: 'Connect a Google Sheets credential and pick the target spreadsheet.',
  googleDrive: 'Connect a Google Drive credential.',
  googleCalendar: 'Connect a Google Calendar credential.',
  slack: 'Add a Slack credential (OAuth or bot token) and select the channel.',
  notion: 'Add a Notion internal-integration token credential.',
  airtable: 'Add an Airtable token credential and choose the base/table.',
  openAi: 'Add your OpenAI API key credential.',
  anthropic: 'Add your Anthropic API key credential.',
  postgres: 'Add database credentials (host, database, user, password).',
  mySql: 'Add database credentials (host, database, user, password).',
  telegram: 'Add a Telegram bot token credential.',
  discord: 'Add a Discord webhook or bot credential.',
  sendGrid: 'Add a SendGrid API key credential.',
  emailSend: 'Configure SMTP credentials to send email.',
  hubspot: 'Add a HubSpot credential.',
  salesforce: 'Add a Salesforce OAuth credential.',
  twilio: 'Add a Twilio credential (account SID + auth token).',
  stripe: 'Add a Stripe API key credential.',
}

function shortType(type: string): string {
  // n8n types look like "n8n-nodes-base.httpRequest" or "@n8n/...langchain.openAi"
  const dot = type.lastIndexOf('.')
  return dot >= 0 ? type.slice(dot + 1) : type
}

function extractNodes(workflowJson: unknown): { name: string; short: string }[] {
  try {
    const wf = workflowJson as { nodes?: unknown }
    const nodes = Array.isArray(wf?.nodes) ? wf.nodes : []
    return nodes
      .map((n) => {
        const node = n as N8nNodeLike
        const type = typeof node?.type === 'string' ? node.type : ''
        const name = typeof node?.name === 'string' ? node.name : (type ? shortType(type) : 'Node')
        return { name, short: type ? shortType(type) : '' }
      })
      .filter((n) => n.short !== 'stickyNote')
  } catch {
    return []
  }
}

export function buildN8nSetupGuide(input: SetupGuideInput): string {
  const title = input.templateName || input.workflowName || 'Automation Workflow'
  const nodes = extractNodes(input.workflowJson)
  const count = nodes.length || input.nodeCount || 0

  // Credential/config lines, de-duplicated by short type.
  const seen = new Set<string>()
  const credLines: string[] = []
  for (const n of nodes) {
    const hint = CRED_HINTS[n.short]
    if (hint && !seen.has(n.short)) {
      seen.add(n.short)
      credLines.push('- **' + n.name + '** (`' + n.short + '`) - ' + hint)
    }
  }

  const L: string[] = []
  L.push('# ' + title + ' - n8n Setup Guide')
  L.push('')
  const ctx = input.taskName ? ' - Task: ' + input.taskName : ''
  L.push('_Generated by WorkScanAI for "' + input.workflowName + '"' + ctx + '._')
  L.push('')
  L.push('## What this does')
  L.push(input.relevanceReason || 'An automation tailored to the task above. Import it into n8n, connect your accounts, and activate.')
  L.push('')
  L.push('## Before you start')
  L.push('- An n8n instance - n8n Cloud (app.n8n.io) or self-hosted.')
  L.push('- ~10 minutes. New to n8n? See https://docs.n8n.io/workflows/import-export/')
  L.push('')
  L.push('## Import the workflow')
  L.push('1. Download the workflow JSON (the **Import into n8n** button next to this guide).')
  L.push('2. In n8n, open **Workflows -> Add workflow -> ... menu -> Import from File**, and pick the JSON.')
  L.push(count ? '3. The workflow loads onto the canvas with all ' + count + ' node(s).' : '3. The workflow loads onto the canvas.')
  L.push('')
  if (nodes.length) {
    L.push('## Nodes in this workflow (' + count + ')')
    for (const n of nodes) {
      L.push(n.short ? '- **' + n.name + '** - `' + n.short + '`' : '- **' + n.name + '**')
    }
    L.push('')
  }
  L.push('## Connect credentials')
  if (credLines.length) {
    L.push('These nodes need a credential or configuration before the workflow will run:')
    L.push('')
    for (const line of credLines) L.push(line)
  } else {
    L.push('No external credentials were detected automatically - still open each node and review its parameters before running.')
  }
  L.push('')
  L.push('## Test & activate')
  L.push('1. Add credentials to the nodes listed above.')
  L.push('2. Click **Execute Workflow** to run it once with sample data and check the output.')
  L.push('3. When it runs cleanly, toggle **Active** (top-right) to put it live.')
  if (input.url) {
    L.push('')
    L.push('## Source')
    L.push('Based on a community-tested template: ' + input.url)
  }
  L.push('')
  L.push('---')
  L.push('Generated by WorkScanAI - workscanai.app - free automation-opportunity analysis.')
  return L.join('\n')
}

export function downloadMarkdown(filename: string, markdown: string): void {
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url)
}
